In [1]:
import pandas as pd
import numpy as np
import datetime
import warnings

warnings.filterwarnings('ignore')
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline  

pd.set_option('display.max_columns', None)

In [2]:
data = pd.read_csv('C:/Users/ivanr/Downloads/lab-cleaning-numerical-data/files_for_lab/we_fn_use_c_marketing_customer_value_analysis.csv')

In [3]:
data.head()

,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,Income,Location Code,Marital Status,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size
0,BU79786,Washington,2763.519279,No,Basic,Bachelor,2/24/11,Employed,F,56274,Suburban,Married,69,32,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,QZ44356,Arizona,6979.535903,No,Extended,Bachelor,1/31/11,Unemployed,F,0,Suburban,Single,94,13,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,AI49188,Nevada,12887.431650,No,Premium,Bachelor,2/19/11,Employed,F,48767,Suburban,Married,108,18,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,WW63253,California,7645.861827,No,Basic,Bachelor,1/20/11,Unemployed,M,0,Suburban,Married,106,18,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,HB64268,Washington,2813.692575,No,Basic,Bachelor,2/3/11,Employed,M,43836,Rural,Single,73,12,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize

In [6]:
data.columns = list(map(lambda x: x.lower().replace(' ', '_'), data.columns))

In [7]:
data.columns

Index(['customer', 'state', 'customer_lifetime_value', 'response', 'coverage',
       'education', 'effective_to_date', 'employmentstatus', 'gender',
       'income', 'location_code', 'marital_status', 'monthly_premium_auto',
       'months_since_last_claim', 'months_since_policy_inception',
       'number_of_open_complaints', 'number_of_policies', 'policy_type',
       'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount',
       'vehicle_class', 'vehicle_size'],
      dtype='object')

In [8]:
data = data.drop(['customer'], axis=1)

In [12]:
data.dtypes

state                                    object
customer_lifetime_value                 float64
response                                 object
coverage                                 object
education                                object
effective_to_date                datetime64[ns]
employmentstatus                         object
gender                                   object
income                                    int64
location_code                            object
marital_status                           object
monthly_premium_auto                      int64
months_since_last_claim                   int64
months_since_policy_inception             int64
number_of_open_complaints                 int64
number_of_policies                        int64
policy_type                              object
policy                                   object
renew_offer_type                         object
sales_channel                            object
total_claim_amount                      float64
vehicle_class                            object
vehicle_size                             object
dtype: object

In [10]:
data['effective_to_date'] = pd.to_datetime(data['effective_to_date'], errors = 'coerce')

In [11]:
data['effective_to_date'].dtype

dtype('<M8[ns]')

In [13]:
data.isna().sum()

state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
dtype: int64

In [14]:
iqr = np.percentile(data['customer_lifetime_value'], 75) - np.percentile(data['customer_lifetime_value'], 25)

In [15]:
iqr

4967.915247000001

In [25]:
u_limit = np.percentile(data['customer_lifetime_value'], 75) + 2.5*iqr

In [26]:
l_limit = np.percentile(data['customer_lifetime_value'], 75) - 2.5*iqr

In [27]:
temp = data[(data['customer_lifetime_value'] < u_limit) & (data['customer_lifetime_value'] > l_limit)]

In [31]:
temp.shape

(8637, 23)

In [29]:
data.shape

(9134, 23)

In [32]:
def remove_outliers(df, col):
    if df[col].dtype == 'int' or df[col].dtype == 'float':
        iqr = np.percentile(df[col], 75) - np.percentile(df[col], 25)
        u_limit = np.percentile(df[col], 75) + 3*iqr
        l_limit = np.percentile(df[col], 25) - 3*iqr
        temp = df[(df[col]> u_limit) | (df[col]<l_limit)]
        if temp.shape[0] < .05*df.shape[0]:
            df = df[(df[col]< u_limit) & (df[col]>l_limit)].reset_index(drop=True)
            return df
        else:
            print('losing too much data')
            return df
    else:
        print('column in not numerical')
        return df

In [37]:
new_data =  remove_outliers(data,'customer_lifetime_value')

In [38]:
new_data.shape

(8767, 23)

In [43]:
data.shape

(8767, 23)

In [40]:
data = new_data

In [42]:
data.reset_index(drop=True)

,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,location_code,marital_status,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size
0,Washington,2763.519279,No,Basic,Bachelor,2011-02-24,Employed,F,56274,Suburban,Married,69,32,5,0,1,Corporate Auto,Corporate L3,Offer1,Agent,384.811147,Two-Door Car,Medsize
1,Arizona,6979.535903,No,Extended,Bachelor,2011-01-31,Unemployed,F,0,Suburban,Single,94,13,42,0,8,Personal Auto,Personal L3,Offer3,Agent,1131.464935,Four-Door Car,Medsize
2,Nevada,12887.431650,No,Premium,Bachelor,2011-02-19,Employed,F,48767,Suburban,Married,108,18,38,0,2,Personal Auto,Personal L3,Offer1,Agent,566.472247,Two-Door Car,Medsize
3,California,7645.861827,No,Basic,Bachelor,2011-01-20,Unemployed,M,0,Suburban,Married,106,18,65,0,7,Corporate Auto,Corporate L2,Offer1,Call Center,529.881344,SUV,Medsize
4,Washington,2813.692575,No,Basic,Bachelor,2011-02-03,Employed,M,43836,Rural,Single,73,12,44,0,1,Personal Auto,Personal L1,Offer1,Agent,138.130879,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8762,California,23405.987980,No,Basic,Bachelor,2011-02-10,Employed,M,71941,Urban,Married,73,18,89,0,2,Personal Auto,Personal L1,Offer2,Web,198.234764,Four-Door Car,Medsize
8763,California,3096.511217,Yes,Extended,College,2011-02-12,Employed,F,21604,Suburban,Divorced,79,14,28,0,1,Corporate Auto,Corporate L3,Offer1,Branch,379.200000,Four-Door Car,Medsize
8764,California,8163.890428,No,Extended,Bachelor,2011-02-06,Unemployed,M,0,Suburban,Single,85,9,37,3,2,Corporate Auto,Corporate L2,Offer1,Branch,790.784983,Four-Door Car,Medsize
8765,California,7524.442436,No,Extended,College,2011-02-03,Employed,M,21941,Suburban,Married,96,34,3,0,3,Personal Auto,Personal L2,Offer3,Branch,691.200000,Four-Door Car,Large
8766,California,2611.836866,No,Extended,College,2011-02-14,Unemployed,M,0,Suburban,Single,77,3,90,0,1,Corporate Auto,Corporate L3,Offer4,Call Center,369.600000,Two-Door Car,Medsize

In [45]:
data_copy = data

In [46]:
data['effective_to_date'][0].year

2011

In [51]:
data['year_from_eff_to_date'] list(map(lambda x: x.year, data['effective_to_date']))

[2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 2011,
 ...]

In [58]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler, Normalizer

In [55]:
numericals = data.select_dtypes(np.number)

In [63]:
categoricals = data.select_dtypes(np.object)
categoricals

,state,response,coverage,education,employmentstatus,gender,location_code,marital_status,policy_type,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size
0,Washington,No,Basic,Bachelor,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,Arizona,No,Extended,Bachelor,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,Nevada,No,Premium,Bachelor,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,California,No,Basic,Bachelor,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,Washington,No,Basic,Bachelor,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8762,California,No,Basic,Bachelor,Employed,M,Urban,Married,Personal Auto,Personal L1,Offer2,Web,Four-Door Car,Medsize
8763,California,Yes,Extended,College,Employed,F,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
8764,California,No,Extended,Bachelor,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,Medsize
8765,California,No,Extended,College,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,Large
8766,California,No,Extended,College,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,Medsize

In [61]:
scaled = Normalizer().fit_transform(numericals)
scaled = pd.DataFrame(scaled)
scaled

,0,1,2,3,4,5,6,7
0,0.049048,0.998772,0.001225,0.000568,0.000089,0.000000,0.000018,0.006830
1,0.987006,0.000000,0.013293,0.001838,0.005939,0.000000,0.001131,0.160005
2,0.255478,0.966747,0.002141,0.000357,0.000753,0.000000,0.000040,0.011230
3,0.997473,0.000000,0.013829,0.002348,0.008480,0.000000,0.000913,0.069128
4,0.064055,0.997940,0.001662,0.000273,0.001002,0.000000,0.000023,0.003145
...,...,...,...,...,...,...,...,...
8762,0.309385,0.950932,0.000965,0.000238,0.001176,0.000000,0.000026,0.002620
8763,0.141858,0.989727,0.003619,0.000641,0.001283,0.000000,0.000046,0.017372
8764,0.995277,0.000000,0.010363,0.001097,0.004511,0.000366,0.000244,0.096406
8765,0.324247,0.945493,0.004137,0.001465,0.000129,0.000000,0.000129,0.029786
8766,0.989138,0.000000,0.029161,0.001136,0.034084,0.000000,0.000379,0.139973

In [65]:
encoded = OneHotEncoder(drop='first').fit_transform(categoricals).toarray()
encoded = pd.DataFrame(encoded) 
encoded

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8762,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8763,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8764,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8765,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8766,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [70]:
data_concat = pd.concat([scaled, encoded], axis = 1)

In [80]:
data_concat.reset_index()

,index,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51
0,0,0.049048,0.998772,0.001225,0.000568,0.000089,0.000000,0.000018,0.006830,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1,1,0.987006,0.000000,0.013293,0.001838,0.005939,0.000000,0.001131,0.160005,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,0.255478,0.966747,0.002141,0.000357,0.000753,0.000000,0.000040,0.011230,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
3,3,0.997473,0.000000,0.013829,0.002348,0.008480,0.000000,0.000913,0.069128,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,4,0.064055,0.997940,0.001662,0.000273,0.001002,0.000000,0.000023,0.003145,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8762,8762,0.309385,0.950932,0.000965,0.000238,0.001176,0.000000,0.000026,0.002620,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8763,8763,0.141858,0.989727,0.003619,0.000641,0.001283,0.000000,0.000046,0.017372,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8764,8764,0.995277,0.000000,0.010363,0.001097,0.004511,0.000366,0.000244,0.096406,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8765,8765,0.324247,0.945493,0.004137,0.001465,0.000129,0.000000,0.000129,0.029786,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8766,8766,0.989138,0.000000,0.029161,0.001136,0.034084,0.000000,0.000379,0.139973,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [72]:
data_concat.columns

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7,  8,
             9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
            26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
            42],
           dtype='int64')

In [77]:
new_col_names = [f'{i}' for i in range(1, len(data_concat.columns) + 1)]

In [78]:
new_col_names

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51']

In [79]:
data_concat.columns = new_col_names